version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 35
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
  identical-code:
    config:
      languages:
        javascript:
          threshold: 5
        typescript:
          threshold: 5
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          count_threshold: 5
        typescript:
          count_threshold: 5
  fixme:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-4"
  tslint:
    enabled: true
    config: tslint.json
  nodesecurity:
    enabled: true
exclude_patterns:
  - "lib/"
  - "node_modules/"
  - "coverage/"
  - "**/*.test.*"
  - ".*/"
  - "*.json"

